export const MEAL_LIST_REQUEST = "MEAL_LIST_REQUEST";
export const MEAL_LIST_SUCCESS = "MEAL_LIST_SUCCESS";
export const MEAL_LIST_FAIL = "MEAL_LIST_FAIL";

export const MEAL_USER_LIST_REQUEST = "MEAL_USER_LIST_REQUEST";
export const MEAL_USER_LIST_SUCCESS = "MEAL_USER_LIST_SUCCESS";
export const MEAL_USER_LIST_FAIL = "MEAL_USER_LIST_FAIL";

export const MEAL_DETAILS_REQUEST = "MEAL_DETAILS_REQUEST";
export const MEAL_DETAILS_SUCCESS = "MEAL_DETAILS_SUCCESS";
export const MEAL_DETAILS_FAIL = "MEAL_DETAILS_FAIL";

export const MEAL_DELETE_REQUEST = "MEAL_DELETE_REQUEST";
export const MEAL_DELETE_SUCCESS = "MEAL_DELETE_SUCCESS";
export const MEAL_DELETE_FAIL = "MEAL_DELETE_FAIL";

export const MEAL_CREATE_REQUEST = "MEAL_CREATE_REQUEST";
export const MEAL_CREATE_SUCCESS = "MEAL_CREATE_SUCCESS";
export const MEAL_CREATE_FAIL = "MEAL_CREATE_FAIL";
export const MEAL_CREATE_RESET = "MEAL_CREATE_RESET";

export const MEAL_UPDATE_REQUEST = "MEAL_UPDATE_REQUEST";
export const MEAL_UPDATE_SUCCESS = "MEAL_UPDATE_SUCCESS";
export const MEAL_UPDATE_FAIL = "MEAL_UPDATE_FAIL";
export const MEAL_UPDATE_RESET = "MEAL_UPDATE_RESET";

export const MEAL_CREATE_REVIEW_REQUEST = "MEAL_CREATE_REVIEW_REQUEST";
export const MEAL_CREATE_REVIEW_SUCCESS = "MEAL_CREATE_REVIEW_SUCCESS";
export const MEAL_CREATE_REVIEW_FAIL = "MEAL_CREATE_REVIEW_FAIL";
export const MEAL_CREATE_REVIEW_RESET = "MEAL_CREATE_REVIEW_RESET";

export const MEAL_TOP_REQUEST = "MEAL_TOP_REQUEST";
export const MEAL_TOP_SUCCESS = "MEAL_TOP_SUCCESS";
export const MEAL_TOP_FAIL = "MEAL_TOP_FAIL";
