export const ROUND_LIST_REQUEST = "ROUND_LIST_REQUEST";
export const ROUND_LIST_SUCCESS = "ROUND_LIST_SUCCESS";
export const ROUND_LIST_FAIL = "ROUND_LIST_FAIL";

export const ROUND_DETAILS_REQUEST = "ROUND_DETAILS_REQUEST";
export const ROUND_DETAILS_SUCCESS = "ROUND_DETAILS_SUCCESS";
export const ROUND_DETAILS_FAIL = "ROUND_DETAILS_FAIL";

export const ROUND_DELETE_REQUEST = "ROUND_DELETE_REQUEST";
export const ROUND_DELETE_SUCCESS = "ROUND_DELETE_SUCCESS";
export const ROUND_DELETE_FAIL = "ROUND_DELETE_FAIL";

export const ROUND_CREATE_REQUEST = "ROUND_CREATE_REQUEST";
export const ROUND_CREATE_SUCCESS = "ROUND_CREATE_SUCCESS";
export const ROUND_CREATE_FAIL = "ROUND_CREATE_FAIL";
export const ROUND_CREATE_RESET = "ROUND_CREATE_RESET";

export const ROUND_UPDATE_REQUEST = "ROUND_UPDATE_REQUEST";
export const ROUND_UPDATE_SUCCESS = "ROUND_UPDATE_SUCCESS";
export const ROUND_UPDATE_FAIL = "ROUND_UPDATE_FAIL";
export const ROUND_UPDATE_RESET = "ROUND_UPDATE_RESET";

export const ROUND_CREATE_REVIEW_REQUEST = "ROUND_CREATE_REVIEW_REQUEST";
export const ROUND_CREATE_REVIEW_SUCCESS = "ROUND_CREATE_REVIEW_SUCCESS";
export const ROUND_CREATE_REVIEW_FAIL = "ROUND_CREATE_REVIEW_FAIL";
export const ROUND_CREATE_REVIEW_RESET = "ROUND_CREATE_REVIEW_RESET";

export const ROUND_TOP_REQUEST = "ROUND_TOP_REQUEST";
export const ROUND_TOP_SUCCESS = "ROUND_TOP_SUCCESS";
export const ROUND_TOP_FAIL = "ROUND_TOP_FAIL";
