const rounds = [
  {
    _id: "1",
    name: "Round 1",
    image: "/images/airpods.jpg",
    description:
      "First Round of the Djangui Please send your money on time the beneficiary will be travelling",
    starting_date: "07-09-2021",
    end_date: "07-15-2021",
    amount_expected: 3000,
    amount_collected: 1500,
    participants: 10,
    numReviews: 5,
    rating: 4.5,
    beneficiary: "Jean Mari",
  },
  {
    _id: "2",
    name: "Round 2",
    image: "/images/mouse.jpg",
    description:
      "Second Round of the Djangui Please send your money on time the beneficiary will be travelling",
    starting_date: "08-09-2021",
    end_date: "08-15-2021",
    amount_expected: 3000,
    amount_collected: 3000,
    participants: 10,
    numReviews: 6,
    rating: 4.5,
    beneficiary: "Maurice Kamto",
  },
  {
    _id: "3",
    name: "Round 3",
    image: "/images/camera.jpg",
    description:
      "Third Round of the Djangui Please send your money on time the beneficiary will be travelling",
    starting_date: "09-09-2021",
    end_date: "09-15-2021",
    amount_expected: 3000,
    amount_collected: 3000,
    participants: 10,
    numReviews: 9,
    rating: 4,
    beneficiary: "Mark Gasol",
  },
  {
    _id: "4",
    name: "Round 4",
    image: "/images/phone.jpg",
    description:
      "Fourth Round of the Djangui Please send your money on time the beneficiary will be travelling",
    starting_date: "10-09-2021",
    end_date: "10-15-2021",
    amount_expected: 3000,
    amount_collected: 3000,
    participants: 10,
    numReviews: 3,
    rating: 3,
    beneficiary: "Lebron James",
  },
  {
    _id: "5",
    name: "Round 5",
    image: "/images/alexa.jpg",
    description:
      "Fifth Round of the Djangui Please send your money on time the beneficiary will be travelling",
    starting_date: "11-09-2021",
    end_date: "11-15-2021",
    amount_expected: 3000,
    amount_collected: 1800,
    participants: 10,
    numReviews: 4,
    rating: 3,
    beneficiary: "Many Bella ",
  },
];

export default rounds;
